Repository LikelionSnuggle/Snuggle-Frontend, pull requests merged in 2023-10, with the labels that each got.

#3 :sparkles: [ADD] Kakao map markers and click event that opens modal
  package-lock.json
  package.json
  src/components/KakaoMap.jsx
  src/components/MapCard.jsx
  src/pages/Map.jsx
Labels: :gift: 기능

#4 :white_check_mark: [ADD] <tailwind css, font> setting
  dist/output.css
  package-lock.json
  package.json
  public/index.html
  src/fonts/IBMPlexSans-Bold.ttf
  src/fonts/IBMPlexSans-BoldItalic.ttf
  src/fonts/IBMPlexSans-ExtraLight.ttf
  src/fonts/IBMPlexSans-ExtraLightItalic.ttf
  src/fonts/IBMPlexSans-Italic.ttf
  src/fonts/IBMPlexSans-Light.ttf
  src/fonts/IBMPlexSans-LightItalic.ttf
  src/fonts/IBMPlexSans-Medium.ttf
  src/fonts/IBMPlexSans-MediumItalic.ttf
  src/fonts/IBMPlexSans-Regular.ttf
  src/fonts/IBMPlexSans-SemiBold.ttf
  src/fonts/IBMPlexSans-SemiBoldItalic.ttf
  src/fonts/IBMPlexSans-Thin.ttf
  src/fonts/IBMPlexSans-ThinItalic.ttf
  src/index.css
  tailwind.config.js
Labels: ⚙️ 설정

#5 [김민혁] - Splash 임시 구현, Global colors 세팅
  src/assets/splash/splash-background.png
  src/assets/splash/splash-icon1.svg
  src/assets/splash/splash-icon2.svg
  src/css/splashTitle.css
  src/pages/Main.jsx
  src/styles/Styles.jsx
  tailwind.config.js
Labels: ⚙️ 설정, :iphone: UI

#7 [김민혁] Splash, Main Screen 퍼블리싱
  src/assets/main-background.png
  src/components/SplashScreen.jsx
  src/css/splashTitle.css
  src/index.css
  src/pages/Main.jsx
  tailwind.config.js
Labels: ⚙️ 설정, :iphone: UI
